# Generated by Django 3.2.4 on 2021-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_trial_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
